### ISSUE TITLE
Global - breadcrumb : Nom de module

### ISSUE THREAD

**Issue by benjaminplanche** [IFAEDI/S.I#1]
Il y a eu une mauvaise interprétation du breadcrumb (la barre donnant la position dans l'arborescence du site, du style "Accueil / Partie / Page")

L'affichage actuel est du type "Accueil / Nom_module / Nom_page" ... Ce qui ne présente pas beaucoup d'intérêt dans beaucoup de cas, vu qu'un module n'a pas énormément des pages différentes, ce qui fait qu'on se retrouve souvent avec des choses du style :
- Accueil / annuaire / annuaire
- Accueil / cvtheque / cvtheque

A la place du nom du module, il serait peut-être plus intéressant pour l'utilisateur de lui donner le nom de la partie du site en rapport, cf la barre de menu. Par exemple :
- Accueil / Entreprise / CVthèque ou Accueil / Etudiant / CVthèque (en fonction si c'est pour une consultation ou un ajout)
- Accueil / AEDI / Annuaire
- Accueil / Entreprise / RIF / Inscription
  _(il est possible d'ajouter plus d'éléments que seulement 3)_

Autre petite remarque, pour la page, au lieu de mettre le nom du fichier (genre annuaire pour annuaire.php), mettre plutôt le titre de la page (genre Annuaire ... mettre une majuscule / des accents, ca rend toujours plus friendly). ;-)

**Comment by zoic21** [comment]
C'est une des question que je me suis pos lintrt de cette barre (je
serais pour l'enlever) mais si tu regarde bien le code les paramtres pass
sont directement li  la page qui va tre appel j'ai fais en sorte que
les majuscule ne gne pas normalement en revanche les accents vont sortir
en erreurs.

Il faudrait donc rajouter des paramtres lors de lappelle d'une page dans
le index.php

Le 25 mars 2012 17:30, Benjamin Planche <
reply@reply.github.com

**Comment by PandiPanda69** [comment]
+1 :-)

Le 25 mars 2012 17:30, Benjamin Planche <
reply@reply.github.com

**Comment by benjaminplanche** [comment]
J'ai l'impression que tu as un soucis d'accentuation ... ^^

Concrètement, ce que je propose, c'est tout simplement :
- Ne pas utiliser $nom_page mais $titre_page, qui rend bien mieux.
- Ajouter, en effet, une variable, genre $titre_module, pour remplace $nom_module dans cette barre (avec $titre_module qui vaudra, pour commencer, soit "Entreprise", soit "Etudiant", soit "AEDI")

Quant à l'utilité du breadcrumb, elle est multiple. Tout d'abord, comme son nom l'indique, ca permet à l'user de savoir où il en est clairement. Ensuite, ce genre de chose est bien aimé par les moteurs de recherche, puisqu'il ajoute à la cohérence intra-site.

**Comment by bnjbvr** [comment]
A noter que le breadcrump en français se traduit "Fil d'Ariane", c'est plus imagé que des miettes de pain ^^
