### ISSUE TITLE
SoGé - Faute d'orthographe

### ISSUE THREAD

**Issue by PandiPanda69** [IFAEDI/S.I#23]
Il y a une faute d'orthographe dans la bannière de la Société Générale à la dernière image:
"TOUS NOS POSTE SONT OUVERTS"

Il manque un "s" à poste.

![image](https://f.cloud.github.com/assets/1172042/128138/42027d58-6fb0-11e2-825d-09af02f94fbf.png)

**Comment by blackheaven** [comment]
je ne sais pas décompiler le flash, désolé
