### ISSUE TITLE
Accueil - Logo Thales énorme

### ISSUE THREAD

**Issue by PandiPanda69** [IFAEDI/S.I#34]
Vue en prod le 08.02.2013 à 17h30

Voir capture:

![image](https://f.cloud.github.com/assets/1172042/140007/c3df5fbc-720d-11e2-8b33-547680f8e2f1.png)

**Comment by benjaminplanche** [comment]
Fixed par la PR #31. Faudrait juste passer la modif' en prod'.

_(Et moi qui pensais abuser des onglets, c'est l'anarchie chez toi Seb ! ^^ Et je suis curieux de savoir ce qu'est le programme "Jeux X..." ? )_

**Comment by blackheaven** [comment]
Fixed by PR #36
