### ISSUE TITLE
Lorem Ipsum en ligne

### ISSUE THREAD

**Issue by benjaminplanche** [IFAEDI/S.I#38]
Les modifications du contenu, remplaçant les Lorem Ipsum, sont sur la branche _contenu-statique_ et n'ont pas encore été mergées avec _master_.
Résultat, la production est bourrée de Lorem Ipsum, ce qui manque un peu de sérieux.

(Sur la branche _contenu-statique_, seule la page _Conférences_ contient encore des place-holders)

**Comment by blackheaven** [comment]
Je suis pour le merge, le plus tôt possible, quelqu'un est contre ?

**Comment by benjaminplanche** [comment]
Faudrait alors aussi merger au préalable la PR #30 pour bloquer les accès aux pages inachevées / modules non en ligne.

**Comment by blackheaven** [comment]
Ça me va, tu veux que je le fasse ?

**Comment by benjaminplanche** [comment]
Ca m'arrangerait, si t'as le temps ... Sinon je peux d'ici 1-2h.

**Comment by blackheaven** [comment]
erf, je ne peux le faire que dans l'après-midi, le premier qui peut poste un message ici histoire de ne pas se marcher sur les pieds.

**Comment by benjaminplanche** [comment]
Fait, plus qu'à cross-checker et mettre en prod'.

**Comment by blackheaven** [comment]
Fait et validé
