### ISSUE TITLE
SQL de création invalide

### ISSUE THREAD

**Issue by blackheaven** [IFAEDI/S.I#57]
Le script SQL de création de la base est invalide, par exemple il manque login à la table utilisateur.

**Comment by bnjbvr** [comment]
Tu as bien utilisé https://github.com/IFAEDI/S.I/blob/master/install/test_set.sql , pas l'ancien script?
Je l'ai testé sur mon ordi et ça marchait très bien.

**Comment by blackheaven** [comment]
Mmmh, je ne suis pas à jour
