### ISSUE TITLE
Contenu - Merge & Mise en production

### ISSUE THREAD

**Issue by benjaminplanche** [IFAEDI/S.I#61]
# Contexte

La branche _contenu-statique_ a recu pas mal de commits enrichissant les descriptions ou améliorant la présentation.
Le contenu _temporaire_ semble plus ou moins finalisé.
# Proposition

Merger cette branche dans _master_ et mettre le tout en production afin de rendre disponibles ces corrections.

**Comment by blackheaven** [comment]
ça me va, donnez moi le top

**Comment by bnjbvr** [comment]
ça me va aussi, dés que tu peux ;)

**Comment by blackheaven** [comment]
fait.
