### ISSUE TITLE
Annuaire - Affichage de la dialog d'erreur systèmatiquement

### ISSUE THREAD

**Issue by PandiPanda69** [IFAEDI/S.I#9]
Lorsque l'on ajoute une entreprise ou un contact dans l'annuaire entreprise, on a systématiquement la dialog d'erreur qui s'affiche (sans afficher d'erreur). En la fermant, on a pourtant la dialogue de réussite qui est affichée, témoignant que tout s'est bien passé.

**Comment by benjaminplanche** [comment]
Hop, résolu.

Lors de ta normalisation des erreurs JSON, t'avais modifié une condition que j'utilisais pour traiter des erreurs avant l'affichage des modifications (suite à n'importe quelle action).

Cette condition était foireuse (inventant une erreur à chaque fois, en voulant checker si un code de retour vaut bien "ok" alors qu'il n'est en fait pas indiqué). J'ai supprimé le code en question (plus de checkage des erreurs donc, mais je crois que de toute façon tu les catches avant maintenant ...). Je crois avoir cassé quelque chose, mais pas vérifié plus que ça ...

**Comment by PandiPanda69** [comment]
Pas de problème, je repasserai ça au test avant de redéployer ;-)

Merci en tout cas pour la rapidité!

Le 22 novembre 2012 14:16, Benjamin Planche notifications@github.com a
écrit :

**Comment by benjaminplanche** [comment]
"Je crois **PAS** avoir cassé quelque chose, mais pas vérifié plus que ça ..." !
Sorry, typo de ma part.
